name: ğŸ“Š ECOS ê¸ˆë¦¬ ë°ì´í„° ìë™ ì—…ë°ì´íŠ¸

on:
  schedule:
    - cron: '5 * * * *'  # ë§¤ì›” 1ì¼ 00:00 UTC (KST ì˜¤ì „ 9ì‹œ)"0 0 1 * *"
  workflow_dispatch:      # ìˆ˜ë™ ì‹¤í–‰ë„ í—ˆìš©

jobs:
  update-interest-rate:
    runs-on: ubuntu-latest

    

    steps:
      - name: ğŸ“ ì €ì¥ì†Œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v4

      - name: ğŸ Python ì„¤ì¹˜
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: ğŸ“¦ í•„ìš”í•œ íŒ¨í‚¤ì§€ ì„¤ì¹˜
        run: |
          pip install pandas requests python-dotenv matplotlib openpyxl

      - name: ğŸ“ˆ ECOS ê¸ˆë¦¬ ë°ì´í„° ìˆ˜ì§‘ ë° README ê°±ì‹ 
        run: python loan_data.py
             python update_loan.py
        env:
          ECOS_KEY: ${{ secrets.ECOS_KEY }}

      - name: ğŸ’¾ ë³€ê²½ì‚¬í•­ ì»¤ë°‹ ë° í‘¸ì‹œ
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md output/
          git commit -m "ğŸ“ˆ README ë° ê¸ˆë¦¬ ë°ì´í„° ìë™ ì—…ë°ì´íŠ¸ ($(date +'%Y-%m-%d'))" || echo "No changes to commit"
          git push